### ISSUE TITLE
Can't click when nested inside a ViewSwitcher

### ISSUE THREAD

**Issue by justinmoon** [Finnerale/druid-enums#2]
Hey,

I'm trying to create an "overlay" based on an enum as described in [this Zulip thread](https://xi.zulipchat.com/#narrow/stream/147926-druid/topic/Enum-based.20Overlays/near/205759384).

I want to create an enum and store it in my app state. When this enum isn't a `OverlayState::None` variant, use a `ViewSwitcher` to display an overlay corresponding to this variant. If it is an `OverlayState::None` variant, just display the normal page.

```
pub enum Overlay {
    Foo(FooOverlayState),
    Bar(BarOverlayState),
    None,
}

pub struct AppState {
    ...
    overlay: Overlay,
    ...
}

fn ui() -> impl Widget<AppState> {
    let view_switcher = ViewSwitcher::new(
        |data: &AppState, _env| data.overlay.clone(),
        |overlay, _data, _env| match overlay {
            OverlayState::None => Box::new(page_ui()),
            _ => Box::new(overlay_ui().lens(AppState::overlay)),
        },
    );
    ...
}
```

But we hit a snag. When the overlay is first presented, it allows you to click one and then all subsequent clicks have no effect. Hovers, however, continue to register.

[Here is minimal reproduction of the issue](https://github.com/justinmoon/druid-enums-bug)

**Comment by luleyleo** [comment]
I'll close this now, thanks for the detailed report.

**Comment by justinmoon** [comment]
Thanks for fixing it!
