### ISSUE TITLE
Multiple layers of enums

### ISSUE THREAD

**Issue by swfsql** [Finnerale/druid-enums#3]
Hello, I came across a possible limitation when multiple layers of enums are used.  
It may be that I'm doing something wrong as well, so I'd appreciate if you could take a look into [this example](https://github.com/swfsql/druid-enums/blob/master/examples/login2.rs).

To run it:

```
git clone https://github.com/swfsql/druid-enums
cd druid-enums
cargo run --example login2
```

This is based on the `login` example, but I forced a situation where multiple enum layers were used: 

```rust
enum AppState {
    Login(LoginState),
    Main(MainState),
}

enum MainState {
    LoggedMainState(LoggedMainState),
    UnloggedMainState(UnloggedMainState),
}
```

Where for the Unlogged state I refrain from labeling the username (as there would be none).

The problem is that after a login (both with or without an username), I can't click the increment button.  
I think it's related to some sort of event propagation problem, but I haven't explored this area from druid..

Please let me know if I'm missing something

**Comment by luleyleo** [comment]
Thanks for the report! Apparently I somehow unwatched my repo here and did not notice this issue until today...

I found the issue and fixed it. Also, widgets are now wrapped into `WidgetPod` and should honor `WidgetAdded` from now on.
